title: "Guida installazione Klipper"
tagline: Guida in italiano installazione Klipper e altri componenti
description: Documentazione in Italiano per l'installazione del Firmware Klipper, Moonraker, Mainsail, Fluidd e altri componenti per Stampanti 3D
remote_theme: pmarsceill/just-the-docs
#remote_theme: mmistakes/minimal-mistakes
logo: "/images/klipper-logo-it.png"
search_enabled: true

# Build settings
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://klipper-italia.xyz" # the base hostname & protocol for your site, e.g. http://example.com
# permalink: pretty
#exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile", "docs/tests/"]

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-target-blank
  - jekyll-include-cache
  
# Aux links for the upper right navigation
aux_links:
  "Torna alla Home":
    - "//klipper-italia.xyz"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Color scheme supports "light" (default) and "dark"
color_scheme: foo

# Back to top link
back_to_top: true
#back_to_top_text: "Back to top"
back_to_top_text: "Torna in cima"

# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust markup / liquid-based content.
footer_content: "Copyright &copy; Guida Installazione Klipper 2020-2021</a>"

# Footer last edited timestamp
# set timezone
timezone: Europe/Rome
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
#last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
#last_edit_time_format: "Sito modificato il %d/%m/%Y alle ore %H:%M %z"
last_edit_time_format: "Utima modifica del %d/%m/%Y alle ore %H:%M"

# Footer "Edit this page on GitHub" link text
gh_edit_link: false # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/sugar012/klipperITA" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      image: images/rtfm.png

# Google Analytics
ga_tracking: UA-6214740-11
