site_name: Klipper Italia
repo_url: https://github.com/morganfw/klipperITA
nav:
    - 'User Documentation':
        - Benvenuto: index.md
        - Configuration : configuration.md
        - User Changes: user_changes.md
    - 'Client Developers':
        - Client API: web_api.md
        - Printer Objects: printer_objects.md
        - API Changes: api_changes.md
    - 'Backend Developers':
        - Contributing: contributing.md
        - Components: components.md
theme:
    name: readthedocs
plugins:
    - search
markdown_extensions:
    - codehilite
    - admonition
